name: "Deploy codigo-facilito"

on:
  push:
    branches: ["main"]

    jobs:
    deploy-codigofacilito:
    runs-on: ubuntu-latest
    steps:
      run: echo "Hacemos correr pull de código"
      run: echo "Correr migraciones"
      run: echo "Generar binario"
      run: echo "publicar versión"