name: "Deploy codigo-facilito"

on:
  push:
    branches: ["main"]

    jobs:
    deploy-codigofacilito:
    runs-on: ubuntu-latest
    steps:
      -uses: actions/checkout@v4
      -run: echo "Hacemos correr pull de código"
      -run: echo "Correr migraciones"
      -run: echo "Generar binario"
      -run: echo "publicar versión"